version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    env_file:
      - .env
    environment:
      SERVER_PORT: $SERVER_PORT
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT

    ports:
      - "3333:3333"
    depends_on:
      - mysql

volumes:
  mysql:
